[package]
name = "database-migrator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { path = "../postgres" }

serde = { version = "1.0.162", features = ["derive"] }
orca-core = { version = "0.20.0", registry = "orcalabs-orcastrator" }
config = "0.13.3"
tokio = { version = "1.28.0", features = ["macros"] }
