version: "3.9"
services:
  postgres:
    image: postgis/postgis:14-3.3-alpine
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 5432:5432
  test-db:
    image: ghcr.io/orcalabs/kyogre/test-postgres
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: dockerfiles/test-db/Dockerfile
  ais-consumer:
    image: gchr.io/orcalabs/kyogre/ais-consumer
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local
    build:
      context: .
      dockerfile: dockerfiles/ais-consumer/Dockerfile
      secrets:
        - source: git-credentials
  database-migrator:
    image: gchr.io/orcalabs/kyogre/database-migrator
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local
    build:
      context: .
      dockerfile: dockerfiles/database-migrator/Dockerfile
      secrets:
        - source: git-credentials
  ais-data-migrator:
    image: gchr.io/orcalabs/kyogre/ais-data-migrator
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local
    build:
      context: .
      dockerfile: dockerfiles/ais-data-migrator/Dockerfile
      secrets:
        - source: git-credentials
  web-api:
    image: gchr.io/orcalabs/kyogre/web-api
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: dockerfiles/web-api/Dockerfile
      secrets:
        - source: git-credentials

secrets:
  git-credentials:
    file: ~/.git-credentials
