version: "3.9"

services:
  postgres:
    image: postgis/postgis:14-3.3-alpine
    shm_size: 1g
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 5432:5432
    command: |
      postgres -c shared_preload_libraries='auto_explain'
               -c auto_explain.log_min_duration=0ms
               -c auto_explain.log_analyze=on
               -c auto_explain.log_buffers=on
               -c auto_explain.log_wal=on
               -c auto_explain.log_timing=on
               -c auto_explain.log_settings=on
               -c auto_explain.log_nested_statements=on
               -c auto_explain.log_triggers=on

  migration-db:
    image: postgis/postgis:14-3.3-alpine
    shm_size: 1g
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 5433:5432

  test-db:
    image: ghcr.io/orcalabs/kyogre/test-postgres
    build:
      context: .
      dockerfile: dockerfiles/test-db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 5434:5432

  ais-consumer:
    image: ghcr.io/orcalabs/kyogre/ais-consumer
    build:
      context: .
      dockerfile: dockerfiles/ais-consumer/Dockerfile
      secrets:
        - source: git-credentials
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local

  engine:
    image: ghcr.io/orcalabs/kyogre/engine
    build:
      context: .
      dockerfile: dockerfiles/engine/Dockerfile
      secrets:
        - source: git-credentials
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local

  duckdb:
    image: ghcr.io/orcalabs/kyogre/duckdb
    build:
      context: .
      dockerfile: dockerfiles/duckdb/Dockerfile
      secrets:
        - source: git-credentials
    volumes:
      - duckdb-data:/duckdb-data
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local

  database-migrator:
    image: ghcr.io/orcalabs/kyogre/database-migrator
    build:
      context: .
      dockerfile: dockerfiles/database-migrator/Dockerfile
      secrets:
        - source: git-credentials
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local

  ais-data-migrator:
    image: ghcr.io/orcalabs/kyogre/ais-data-migrator
    build:
      context: .
      dockerfile: dockerfiles/ais-data-migrator/Dockerfile
      secrets:
        - source: git-credentials
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local

  fishery-api:
    image: ghcr.io/orcalabs/kyogre/fishery-api
    build:
      context: .
      dockerfile: dockerfiles/fishery-api/Dockerfile
      secrets:
        - source: git-credentials
    environment:
      - RUST_BACKTRACE=1
      - APP_ENVIRONMENT=local
    ports:
      - 8080:8080

secrets:
  git-credentials:
    file: ~/.git-credentials
volumes:
    duckdb-data:
