log_level: Info
api:
  ip: 0.0.0.0
  port: 8080
postgres:
  port: 5432
  db_name: kyogre
  max_connections: 10
  log_statements: Disable
telemetry:
  ip: api.honeycomb.io
  port: 443
bw_jwks_url: https://id.barentswatch.no/.well-known/openid-configuration/jwks
bw_profiles_url: https://www.barentswatch.no/bwapi/v2/user/profiles
duck_db:
  max_connections: 10
  mode: MissOnError
  storage: Memory
  refresh_schedule:
    Daily: 10:00:00
