log_level: Info
api:
  ip: 0.0.0.0
  port: 8080
postgres:
  ip: orca-postgres-dev.postgres.database.azure.com
  port: 5432
  db_name: kyogre
  max_connections: 10
  log_statements: Disable
telemetry:
  ip: api.honeycomb.io
  port: 443
bw_jwks_url: https://id.barentswatch.no/.well-known/openid-configuration/jwks
bw_profiles_url: https://www.barentswatch.no/bwapi/v2/user/profiles
duck_db_api:
  ip: dev-kyogre-duck-db
  port: 80
auth0:
  jwk_url: https://dev-orcalabs.eu.auth0.com/.well-known/jwks.json
  authorization_url: https://dev-orcalabs.eu.auth0.com/authorize
  client_id: QYCH29iCoaNEfvYWmVMs2m3vbpUv9Gug
  audience: https://api.dev.datafangst.orcalabs.no/
