log_level: Debug
api:
  ip: 0.0.0.0
  port: 8080
postgres:
  ip: postgres
  port: 5432
  username: postgres
  password: test123
  max_connections: 10
  log_statements: Enable
bw_jwks_url: https://id.barentswatch.no/.well-known/openid-configuration/jwks
bw_profiles_url: https://www.barentswatch.no/bwapi/v2/user/profiles
