log_level: Debug
api:
  ip: 0.0.0.0
  port: 8080
postgres:
  ip: postgres
  port: 5432
  username: postgres
  password: test123
  max_connections: 10
  log_statements: Enable
meilisearch:
  host: http://meilisearch:7700
  api_key: test123
bw_jwks_url: https://id.barentswatch.no/.well-known/openid-configuration/jwks
bw_profiles_url: https://www.barentswatch.no/bwapi/v2/user/profiles
duck_db_api:
  ip: duckdb
  port: 5000
auth0:
  jwk_url: https://dev-orcalabs.eu.auth0.com/.well-known/jwks.json
  authorization_url: https://dev-orcalabs.eu.auth0.com/authorize
  client_id: QYCH29iCoaNEfvYWmVMs2m3vbpUv9Gug
  audience: https://api.dev.datafangst.orcalabs.no/
