log_level: Debug
api:
  ip: 0.0.0.0
  port: 8080
postgres:
  ip: localhost
  port: 5532
  username: postgres
  password: test123
  max_connections: 10
  log_statements: Enable
  application_name: kyogre-api
meilisearch:
  host: http://localhost:7700
  api_key: test123
bw_settings:
  jwks_url: https://id.barentswatch.no/.well-known/openid-configuration/jwks
  audience: api
  profiles_url: https://www.barentswatch.no/bwapi/v2/user/profiles
duck_db_api:
  ip: localhost
  port: 5000
auth0:
  jwk_url: https://dev-orcalabs.eu.auth0.com/.well-known/jwks.json
  authorization_url: https://dev-orcalabs.eu.auth0.com/authorize
  client_id: QYCH29iCoaNEfvYWmVMs2m3vbpUv9Gug
  audience: https://api.dev.datafangst.orcalabs.no/
cache_error_mode: Log
