log_level: Info
postgres:
  port: 5432
  db_name: kyogre
  max_connections: 1
  log_statements: Disable
telemetry:
  ip: api.honeycomb.io
  port: 443
engine:
  scrape_schedule:
    Periodic: 1h
scraper:
  ers_dca:
    min_year: 2020
    max_year: 2023
  ers_dep:
    min_year: 2020
    max_year: 2023
  ers_por:
    min_year: 2020
    max_year: 2023
  landings:
    min_year: 2021
    max_year: 2023
