log_level: Info
num_workers: 8
tracing_mode: Regular
fishing_predictors:
  training_rounds: 200
  training_mode:
    Batches: 1000
postgres:
  ip: orca-postgres-dev.postgres.database.azure.com
  port: 5432
  db_name: kyogre
  max_connections: 10
  log_statements: Disable
  application_name: kyogre-engine
telemetry:
  ip: api.honeycomb.io
  port: 443
scraper:
  file_download_dir: '/tmp/kyogre-engine-download-data'
  fishing_facility:
    url: https://www.barentswatch.no/bwapi/v2/geodata/fishingfacilityupdates
    auth_url: 'https://id.barentswatch.no/connect/authorize'
    token_url: 'https://id.barentswatch.no/connect/token'
    scope: 'api'
  fishing_facility_historic:
    url: https://www.barentswatch.no/bwapi/v1/geodata/fishingfacilityhistoric
    auth_url: 'https://id.barentswatch.no/connect/authorize'
    token_url: 'https://id.barentswatch.no/connect/token'
    scope: 'api'
  register_vessels_url: https://api.fiskeridir.no/vessel-api/api/v1/vessels
  aqua_culture_register_url: 'https://api.fiskeridir.no/pub-aqua/api/v1/dump/new-legacy-csv'
  mattilsynet_fishery_url: 'https://mattilsynet-xp7prod.enonic.cloud/api/_/attachment/inline/59b2d10e-8246-476b-a8f9-589f028e2767:2e8d15e8e8e31941d1ca952d7f3694e6880b67b2/Fishery_products.csv'
  mattilsynet_businesses_url: 'https://mattilsynet-xp7prod.enonic.cloud/api/_/attachment/inline/0213bd0e-f035-4d10-8147-bb03193e73bc:2723b89b3f2128c3857502d4fa793588feb24841/virksomhetslister.csv'
  mattilsynet_urls:
    # - "https://www.mattilsynet.no/language/english/food_and_water/approved_products_and_establishments/?kategori=1011&liste=10051#godkjenninger"
    # - "https://www.mattilsynet.no/language/english/food_and_water/approved_products_and_establishments/?kategori=1002&liste=10204#godkjenninger"
  landings:
    min_year: 2000
    max_year: 2024
  ers:
    min_year: 2011
    max_year: 2024
  vms:
    - year: 2024
      url: https://register.fiskeridir.no/vms-ers/2024-VMS.csv.zip
    - year: 2023
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/458958c9-b0a3-4bb6-9457-72a898f681b6:a087911b8c6b76b4cf69eab64a33f0e8250abd4a/2023-VMS.zip
    - year: 2021
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/d8736f20-309c-4b29-9786-a8d8271418c4:300bd8f940c7856c2fbeb4b2053d4fcd989f43e2/posisjonsrapportering-vms-2021-pos.zip
    - year: 2020
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/6cba325a-4f84-4002-905a-7f25d4a6cfca:75ca7ee9be41703018c77cfc6ffa61d2d9c89b54/posisjonsrapportering-vms-2020-pos.zip
    - year: 2019
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/46c58ae4-ef97-4341-8091-c0e6e2a91398:349529ab7b91aec15b07f395222854257186bdf8/posisjonsrapportering-vms-2019-pos.zip
    - year: 2018
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/58039e8f-8b3b-469c-bafa-242f8076fefb:4fd644cf9e8c2aba415a0dc7d6e278d0e6152c39/posisjonsrapportering-vms-2018-pos.zip
    - year: 2017
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/150d09d9-1d6c-4168-953d-9266b2aaa120:97ad1c34216cc01af9804fc7221f079b427f0bbc/posisjonsrapportering-vms-2017-pos.zip
    - year: 2016
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/fe17a8a2-eed3-43a4-868d-c84699d50953:16922efa37906d3096c174481c884d90d5e3abe1/posisjonsrapportering-vms-2016-pos.zip
    - year: 2015
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/a89b811e-76cf-4660-8d27-ee7bf44ecd1c:42441a3d6e044f750019e8c033d2041445211454/posisjonsrapportering-vms-2015-pos.zip
    - year: 2014
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/45ce7608-5b72-4b61-9894-73a5d7ebe77c:b0fd74ccc40eefad69ba3c30a59e296ac00bca42/posisjonsrapportering-vms-2014-pos.zip
    - year: 2013
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/d963aac6-8b02-4c21-a694-ce506bd735c0:cf0e61502e0f38728e7fb81508551f9cf0023036/posisjonsrapportering-vms-2013-pos.zip
    - year: 2012
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/f51512f5-5387-4311-955a-4d27503989bf:bcb1aa871de370dbbd7be50851f31d308d1e4015/posisjonsrapportering-vms-2012-pos.zip
    - year: 2011
      url: https://www.fiskeridir.no/Tall-og-analyse/AApne-data/posisjonsrapportering-vms/_/attachment/download/a6d73f29-21ad-44a1-b328-aec19fd62744:9d2f30adddd2bf8f2eb14e15e480df8df3c2415a/posisjonsrapportering-vms-2011-pos.zip
