log_level: Info
num_trip_state_workers: 2
tracing_mode: Regular
fishing_predictors:
  training_rounds: 200
  training_mode:
    Batches: 1000
postgres:
  ip: kyogre-dev.postgres.database.azure.com
  port: 5432
  db_name: kyogre
  max_connections: 10
  log_statements: Disable
  application_name: kyogre-engine
telemetry:
  ip: api.honeycomb.io
  port: 443
scraper:
  file_download_dir: '/tmp/kyogre-engine-download-data'
  rafisklaget_weekly_sales:
    url: https://ws.rafisklaget.no/statistics/sales-data/weekly-sales
    auth_url: https://ws.rafisklaget.no/statistics/oauth/authorize
    token_url: https://ws.rafisklaget.no/statistics/oauth/token
    scope: ''
  fishing_facility:
    url: https://www.barentswatch.no/bwapi/v2/geodata/fishingfacilityupdates
    auth_url: 'https://id.barentswatch.no/connect/authorize'
    token_url: 'https://id.barentswatch.no/connect/token'
    scope: 'api'
  fishing_facility_historic:
    url: https://www.barentswatch.no/bwapi/v1/geodata/fishingfacilityhistoric
    auth_url: 'https://id.barentswatch.no/connect/authorize'
    token_url: 'https://id.barentswatch.no/connect/token'
    scope: 'api'
  register_vessels_url: https://api.fiskeridir.no/vessel-api/api/v1/vessels
  buyer_register_url: https://api.fiskeridir.no/buyer-api/v1/locations
  aqua_culture_register_url: 'https://api.fiskeridir.no/pub-aqua/api/v1/dump/new-legacy-csv'
  mattilsynet_fishery_url: 'https://mattilsynet-xp7prod.enonic.cloud/api/_/attachment/inline/59b2d10e-8246-476b-a8f9-589f028e2767:2e8d15e8e8e31941d1ca952d7f3694e6880b67b2/Fishery_products.csv'
  mattilsynet_businesses_url: 'https://mattilsynet-xp7prod.enonic.cloud/api/_/attachment/inline/0213bd0e-f035-4d10-8147-bb03193e73bc:2723b89b3f2128c3857502d4fa793588feb24841/virksomhetslister.csv'
  mattilsynet_urls:
    # - "https://www.mattilsynet.no/language/english/food_and_water/approved_products_and_establishments/?kategori=1011&liste=10051#godkjenninger"
    # - "https://www.mattilsynet.no/language/english/food_and_water/approved_products_and_establishments/?kategori=1002&liste=10204#godkjenninger"
  landings:
    min_year: 2000
    max_year: 2025
  ers:
    min_year: 2011
    max_year: 2025
