log_level: Debug
postgres:
  ip: test-db
  port: 5432
  username: postgres
  password: test123
  max_connections: 10
  log_statements: Enable
engine:
  scrape_schedule:
    Periodic: 10m
scraper:
  ers_dca:
    min_year: 2020
    max_year: 2023
  ers_dep:
    min_year: 2020
    max_year: 2023
  ers_por:
    min_year: 2020
    max_year: 2023
  landings:
    min_year: 2021
    max_year: 2023
