log_level: Debug
postgres:
  ip: 127.0.0.1
  port: 5433
  username: postgres
  password: test123
  max_connections: 10
  log_statements: Disable
engine:
  scrape_schedule:
    Periodic: 30s
scraper:
  landings:
    min_year: 2008
    max_year: 2023
