log_level: Info
num_fuel_estimation_workers: 4
tracing_mode: Regular
postgres:
  ip: kyogre-dev.postgres.database.azure.com
  port: 5432
  db_name: kyogre
  max_connections: 10
  log_statements: Disable
  application_name: kyogre-fuel-processor
