[package]
name = "fiskeridir-rs"
version = "0.22.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
utoipa = ["dep:utoipa"]
sqlx = ["dep:sqlx"]

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_with = "3.9.0"
remain = "0.2.14"
chrono = { version = "0.4.38", features = ["serde"] }
jurisdiction = "0.1.1"
serde_repr = "0.1.19"
num-derive = "0.4.2"
num-traits = "0.2.19"
chrono-tz = "0.9.0"
thiserror = "1.0.63"
error-stack = "0.5.0"
futures-util = "0.3.30"
sha3 = "0.10.8"
zip = "2.2.0"
csv = "1.3.0"
reqwest = { workspace = true, features = ["stream", "json", "rustls-tls"] }
tracing = "0.1.40"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
regex = "1.10.6"
once_cell = "1.19.0"

utoipa = { version = "4.2", optional = true }
sqlx = { version = "0.8.1", features = [
    "runtime-tokio-rustls",
    "postgres",
], optional = true }

enum_index = "0.2.0"
enum_index_derive = "0.2.0"

[dev-dependencies]
tokio = { version = "1.39.3", features = ["time", "rt-multi-thread", "macros"] }
wiremock = "0.6.1"
tempfile = "3.12.0"
reqwest = { workspace = true, features = ["stream", "json"] }
