[package]
name = "fiskeridir-rs"
version = "0.22.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
utoipa = ["dep:utoipa"]
sqlx = ["dep:sqlx"]

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_with = "3.4.0"
remain = "0.2.11"
chrono = { version = "0.4.31", features = ["serde"] }
jurisdiction = "0.1.1"
serde_repr = "0.1.17"
num-derive = "0.4.1"
num-traits = "0.2.17"
chrono-tz = "0.8.4"
bigdecimal = { version = "0.3.1", features = ["serde"] }
thiserror = "1.0.51"
error-stack = "0.4.1"
futures-util = "0.3.30"
sha3 = "0.10.8"
zip = "0.6.6"
csv = "1.3.0"
reqwest = { version = "0.11.23", features = ["stream", "json"] }
tracing = "0.1.40"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25"
regex = "1.10.2"
once_cell = "1.19.0"

utoipa = { version = "4.1", optional = true }
sqlx = { version = "0.7.3", features = [
    "runtime-tokio-rustls",
    "postgres",
], optional = true }

enum_index = "0.2.0"
enum_index_derive = "0.2.0"

[dev-dependencies]
tokio = { version = "1.35.1", features = ["time", "rt-multi-thread", "macros"] }
wiremock = "0.5.22"
tempfile = "3.8.1"
