[package]
name = "gen-test-data"
version = "0.1.0"
edition = "2021"

[dependencies]
orca-core = { workspace = true }
engine = { path = "../engine", features = ["test"] }
postgres = { path = "../postgres" }
tokio = "1.41"
clap = { version = "4.5.21", features = ["derive"] }
