[package]
name = "ais-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.59"
serde = "1.0.149"
chrono = { version = "0.4.23", features = ["serde"] }
