log_level: Info
chunk_size: 30d
start_threshold: 2024-09-03T00:00:00Z
end_threshold: 2024-09-04T00:00:00Z
source:
  ip: localhost
  port: 5432
  username: postgres
  password: test123
  max_connections: 32
  log_statements: Disable
  application_name: kyogre-ais-data-migrator
destination:
  ip: orca-postgres-dev.postgres.database.azure.com
  port: 5432
  db_name: kyogre
  max_connections: 32
  log_statements: Disable
  application_name: kyogre-ais-data-migrator
