log_level: Info
chunk_size: 30d
start_threshold: 2025-06-16T03:54:16.904+0200
end_threshold: 2025-06-16T08:05:45.832+0200
source:
  barentswatch:
    ais_positions_url: https://historic.ais.barentswatch.no/open/v1/historic/tracks
    oauth:
      auth_url: https://id.barentswatch.no/connect/authorization
      token_url: https://id.barentswatch.no/connect/token
      scope: ais
  # postgres:
  #   ip: localhost
  #   port: 5532
  #   username: postgres
  #   password: test123
  #   max_connections: 32
  #   log_statements: Disable
  #   application_name: kyogre-ais-data-migrator
destination:
  ip: kyogre-dev.postgres.database.azure.com
  port: 5432
  db_name: kyogre
  max_connections: 32
  log_statements: Disable
  application_name: kyogre-ais-data-migrator
