log_level: "Info"
api_address: https://live.ais.barentswatch.no/live/v1/ais
oauth:
  auth_url: "https://id.barentswatch.no/connect/authorize"
  token_url: "https://id.barentswatch.no/connect/token"
  scope: "ais"
postgres:
  ip: orca-postgres-dev.postgres.database.azure.com
  max_connections: 1
  port: 5432
  db_name: kyogre
  log_statements: "Disable"
  application_name: kyogre-ais-consumer
commit_interval: 10s
broadcast_buffer_size: 100
