[package]
name = "kyogre-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
utoipa = ["dep:utoipa"]
sqlx = ["dep:sqlx"]

[dependencies]
machine = { version = "0.1.3", registry = "orcalabs-orcastrator" }

async-trait = "0.1.73"
serde = { version = "1.0.188", features = ["derive"] }
chrono = { version = "0.4.28", features = ["serde"] }
chrono-tz = "0.8.3"
fiskeridir-rs = { workspace = true }
tokio = { version = "1.32.0", features = ["sync"] }
orca-core = { workspace = true }
humantime = "2.1.0"

serde_repr = "0.1.16"
strum = { version = "0.25.0", features = ["derive"] }
num-traits = "0.2.16"
num-derive = "0.4.0"
error-stack = { workspace = true }
rand = "0.8.5"
futures = "0.3.28"

utoipa = { version = "3.5", optional = true }
remain = "0.2.11"
sqlx = { workspace = true, optional = true }
enum_index = "0.2.0"
enum_index_derive = "0.2.0"
wkt = "0.10.3"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
oauth2 = "4.4.1"
geo = "0.26.0"
tracing = "0.1.37"
