[package]
name = "kyogre-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
utoipa = ["dep:utoipa"]
sqlx = ["dep:sqlx"]

[dependencies]
async-trait = "0.1.71"
serde = { version = "1.0.171", features = ["derive"] }
chrono = { version = "0.4.26", features = ["serde"] }
chrono-tz = "0.8.3"
fiskeridir-rs = { workspace = true }

serde_repr = "0.1.14"
strum = { version = "0.24.1", features = ["derive"] }
num-traits = "0.2.15"
num-derive = "0.3.3"
error-stack = { workspace = true }
rand = "0.8.5"
futures = "0.3.28"

utoipa = { version = "3.4", optional = true }
remain = "0.2.10"
sqlx = { version = "0.6.3", features = [
    "runtime-tokio-rustls",
    "postgres",
    "bigdecimal",
    "chrono",
    "offline",
    "json",
], optional = true }
enum_index = "0.2.0"
enum_index_derive = "0.2.0"
wkt = "0.10.3"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
oauth2 = "4.4.1"
geo = "0.25.1"
