[package]
name = "kyogre-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.63"
serde = "1.0.152"
chrono = { version = "0.4.23", features = ["serde"] }

serde_repr = "0.1.10"
strum = { version = "0.24.1", features = ["derive"] }
num-traits = "0.2.15"
num-derive = "0.3.3"
error-stack = "0.2.4"
rand = "0.8.5"
