[package]
name = "kyogre-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
utoipa = ["dep:utoipa"]
sqlx = ["dep:sqlx"]

[dependencies]
# machine = { version = "0.1.3", registry = "orcalabs-orcastrator" }

async-trait = "0.1.74"
serde = { version = "1.0.193", features = ["derive"] }
chrono = { version = "0.4.31", features = ["serde"] }
chrono-tz = "0.8.4"
fiskeridir-rs = { workspace = true }
tokio = { version = "1.34.0", features = ["sync"] }
orca-core = { workspace = true }

serde_json = "1.0.108"
serde_repr = "0.1.17"
strum = { version = "0.25.0", features = ["derive"] }
num-traits = "0.2.17"
num-derive = "0.4.1"
error-stack = { workspace = true }
rand = "0.8.5"
futures = "0.3.29"

utoipa = { version = "4.1", optional = true }
remain = "0.2.11"
sqlx = { workspace = true, optional = true }
enum_index = "0.2.0"
enum_index_derive = "0.2.0"
wkt = "0.10.3"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
oauth2 = "4.4.2"
geo = "0.26.0"
tracing = "0.1.40"
flate2 = "1.0.28"
vpsearch = "2.0.1"
