[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kyogre-core = { path = "../kyogre-core", features = ["sqlx"] }

orca-core = { workspace = true, features = ["telemetry"] }
fiskeridir-rs = { workspace = true }
jurisdiction = "0.1.1"

num-traits = "0.2.16"
chrono = { version = "0.4.26", features = ["serde"] }
sqlx = { version = "0.6.3", features = [
    "runtime-tokio-rustls",
    "postgres",
    "bigdecimal",
    "chrono",
    "offline",
    "json",
    "uuid",
] }
error-stack = { workspace = true }
bigdecimal = "0.3.1"
tokio = { version = "1.29.1", features = ["macros", "sync", "time"] }
tracing = "0.1.37"
async-trait = "0.1.72"
serde_json = "1.0.103"
serde = { version = "1.0.175", features = ["derive"] }
futures = "0.3.28"
rand = "0.8.5"
strum = "0.24.1"
enum_index = "0.2.0"
enum_index_derive = "0.2.0"
geozero = { version = "0.9.9", features = ["with-postgis-sqlx"] }
geo-types = "0.7.11"
wkt = { version = "0.10.3", features = ["serde"] }
uuid = { version = "1.4.1", features = ["serde"] }

[dev-dependencies]
rand = "0.8.5"
dockertest = { version = "0.3.1", registry = "orcalabs-orcastrator" }
orca-core = { workspace = true, features = ["dockertest"] }
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }
