[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kyogre-core = { path = "../kyogre-core", features = ["sqlx"] }

orca-core = { registry = "orcalabs-orcastrator", version = "0.20.0", features = [
    "telemetry",
] }
fiskeridir-rs = { workspace = true }
jurisdiction = "0.1.1"

num-traits = "0.2.15"
chrono = { version = "0.4.24", features = ["serde"] }
sqlx = { version = "0.6.3", features = [
    "runtime-tokio-rustls",
    "postgres",
    "bigdecimal",
    "chrono",
    "offline",
    "json",
] }
error-stack = { workspace = true }
bigdecimal = "0.3.0"
tokio = { version = "1.27.0", features = ["macros", "sync", "time"] }
tracing = "0.1.37"
async-trait = "0.1.68"
serde_json = "1.0.96"
serde = { version = "1.0.160", features = ["derive"] }
futures = "0.3.28"
rand = "0.8.5"

[dev-dependencies]
rand = "0.8.5"
dockertest = { version = "0.3.1", registry = "orcalabs-orcastrator" }
orca-core = { version = "0.20.0", registry = "orcalabs-orcastrator", features = [
    "dockertest",
] }
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
