[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kyogre-core = { path = "../kyogre-core", features = ["sqlx"] }

orca-core = { workspace = true, features = ["telemetry"] }
fiskeridir-rs = { workspace = true }
jurisdiction = "0.1.1"
unnest_insert = { version = "0.2.3", registry = "orcalabs-orcastrator", features = [
    "derive",
] }

num-traits = "0.2.17"
chrono = { version = "0.4.31", features = ["serde"] }
error-stack = { workspace = true }
bigdecimal = "0.3.1"
tokio = { version = "1.35.1", features = ["macros", "sync", "time"] }
sqlx = { workspace = true }
tracing = "0.1.40"
async-trait = "0.1.76"
serde_json = "1.0.109"
serde = { version = "1.0.193", features = ["derive"] }
futures = "0.3.30"
rand = "0.8.5"
strum = "0.25.0"
enum_index = "0.2.0"
enum_index_derive = "0.2.0"
geozero = { version = "0.11.0", features = ["with-postgis-sqlx"] }
geo-types = "0.7.12"
wkt = { version = "0.10.3", features = ["serde"] }
uuid = { version = "1.6.1", features = ["serde"] }

[dev-dependencies]
rand = "0.8.5"
dockertest = { workspace = true }
orca-core = { workspace = true, features = ["dockertest"] }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
