CREATE TABLE
    ers_tra (
        message_id BIGINT PRIMARY KEY,
        message_date date NOT NULL,
        message_number INT NOT NULL,
        message_time TIME NOT NULL,
        message_timestamp timestamptz NOT NULL,
        ers_message_type_id VARCHAR NOT NULL REFERENCES ers_message_types (ers_message_type_id),
        message_year INT NOT NULL,
        relevant_year INT NOT NULL,
        sequence_number INT,
        reloading_date date,
        reloading_time TIME,
        reloading_timestamp timestamptz,
        fiskeridir_vessel_id BIGINT REFERENCES fiskeridir_vessels (fiskeridir_vessel_id),
        vessel_building_year INT,
        vessel_call_sign VARCHAR CHECK (vessel_call_sign <> ''),
        vessel_call_sign_ers VARCHAR NOT NULL CHECK (vessel_call_sign_ers <> ''),
        vessel_engine_building_year INT,
        vessel_engine_power INT,
        vessel_gross_tonnage_1969 INT,
        vessel_gross_tonnage_other INT,
        vessel_county VARCHAR CHECK (vessel_county <> ''),
        vessel_county_code INT,
        vessel_greatest_length DECIMAL,
        vessel_identification VARCHAR CHECK (vessel_identification <> ''),
        vessel_length DECIMAL NOT NULL,
        vessel_length_group VARCHAR CHECK (vessel_length_group <> ''),
        vessel_length_group_code INT,
        vessel_material_code VARCHAR CHECK (vessel_material_code <> ''),
        vessel_municipality VARCHAR CHECK (vessel_municipality <> ''),
        vessel_municipality_code INT,
        vessel_name VARCHAR CHECK (vessel_name <> ''),
        vessel_name_ers VARCHAR CHECK (vessel_name_ers <> ''),
        vessel_nationality_code VARCHAR CHECK (vessel_nationality_code <> ''),
        fiskeridir_vessel_nationality_group_id INT NOT NULL REFERENCES fiskeridir_vessel_nationality_groups (fiskeridir_vessel_nationality_group_id),
        vessel_rebuilding_year INT,
        vessel_registration_id VARCHAR CHECK (vessel_registration_id <> ''),
        vessel_registration_id_ers VARCHAR CHECK (vessel_registration_id_ers <> ''),
        vessel_valid_until date,
        vessel_valid_from date,
        vessel_width DECIMAL
    );

CREATE TABLE
    ers_tra_catches (
        message_id BIGINT NOT NULL REFERENCES ers_tra (message_id),
        ers_quantum_type_id VARCHAR NOT NULL REFERENCES ers_quantum_types (ers_quantum_type_id),
        living_weight INT NOT NULL,
        species_fao_id VARCHAR NOT NULL REFERENCES species_fao (species_fao_id),
        species_fiskeridir_id INT REFERENCES species_fiskeridir (species_fiskeridir_id),
        species_group_id INT REFERENCES species_groups (species_group_id),
        species_main_group_id INT REFERENCES species_main_groups (species_main_group_id),
        PRIMARY KEY (message_id, species_fao_id)
    );
