ALTER TABLE trips_detailed
DROP COLUMN landing_total_living_weight,
DROP COLUMN landing_total_gross_weight,
DROP COLUMN landing_total_product_weight;

ALTER TABLE hauls
DROP COLUMN vessel_length_group;

ALTER TABLE fiskeridir_vessels
DROP COLUMN fiskeridir_length_group_id;

DROP FUNCTION SUM_WEIGHT,
TO_VESSEL_LENGTH_GROUP;

CREATE
OR REPLACE FUNCTION SUM_WEIGHT (source JSONB, field TEXT) RETURNS DOUBLE PRECISION LANGUAGE PLPGSQL IMMUTABLE AS $$
    BEGIN
        RETURN (
            SELECT
                COALESCE(SUM(c[field]::DOUBLE PRECISION), 0)
            FROM
                JSONB_ARRAY_ELEMENTS(source) c
        );
    END;
$$;

CREATE
OR REPLACE FUNCTION TO_VESSEL_LENGTH_GROUP (vessel_length DOUBLE PRECISION) RETURNS INT LANGUAGE PLPGSQL IMMUTABLE AS $$
    BEGIN
        RETURN
            CASE
                WHEN vessel_length IS NULL THEN 0
                WHEN vessel_length < 11 THEN 1
                WHEN vessel_length::NUMERIC <@ numrange(11, 15, '[)') THEN 2
                WHEN vessel_length::NUMERIC <@ numrange(15, 21, '[)') THEN 3
                WHEN vessel_length::NUMERIC <@ numrange(21, 28, '[)') THEN 4
            ELSE 5
        END;
    END;
$$;

ALTER TABLE trips
ALTER COLUMN distance TYPE DOUBLE PRECISION;

ALTER TABLE trips_detailed
ALTER COLUMN distance TYPE DOUBLE PRECISION,
ADD COLUMN landing_total_living_weight DOUBLE PRECISION GENERATED ALWAYS AS (SUM_WEIGHT (landings, 'living_weight')) STORED,
ADD COLUMN landing_total_product_weight DOUBLE PRECISION GENERATED ALWAYS AS (SUM_WEIGHT (landings, 'product_weight')) STORED,
ADD COLUMN landing_total_gross_weight DOUBLE PRECISION GENERATED ALWAYS AS (SUM_WEIGHT (landings, 'gross_weight')) STORED;

ALTER TABLE landings
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION,
ALTER COLUMN sales_team_tax TYPE DOUBLE PRECISION;

ALTER TABLE landing_entries
ALTER COLUMN withdrawn_catch_value TYPE DOUBLE PRECISION,
ALTER COLUMN catch_value TYPE DOUBLE PRECISION,
ALTER COLUMN sales_team_fee TYPE DOUBLE PRECISION,
ALTER COLUMN post_payment TYPE DOUBLE PRECISION,
ALTER COLUMN support_fee_for_fisher TYPE DOUBLE PRECISION,
ALTER COLUMN price_for_buyer TYPE DOUBLE PRECISION,
ALTER COLUMN price_for_fisher TYPE DOUBLE PRECISION,
ALTER COLUMN unit_price_for_buyer TYPE DOUBLE PRECISION,
ALTER COLUMN unit_price_for_fisher TYPE DOUBLE PRECISION,
ALTER COLUMN product_weight TYPE DOUBLE PRECISION,
ALTER COLUMN product_weight_over_quota TYPE DOUBLE PRECISION,
ALTER COLUMN gross_weight TYPE DOUBLE PRECISION,
ALTER COLUMN living_weight TYPE DOUBLE PRECISION,
ALTER COLUMN living_weight_over_quota TYPE DOUBLE PRECISION;

ALTER TABLE ers_arrivals
ALTER COLUMN vessel_greatest_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_width TYPE DOUBLE PRECISION;

ALTER TABLE ers_departures
ALTER COLUMN vessel_greatest_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_width TYPE DOUBLE PRECISION;

ALTER TABLE ers_tra
ALTER COLUMN vessel_greatest_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_width TYPE DOUBLE PRECISION;

ALTER TABLE ers_dca
ALTER COLUMN vessel_greatest_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_width TYPE DOUBLE PRECISION;

ALTER TABLE ers_dca_bodies
ALTER COLUMN start_latitude TYPE DOUBLE PRECISION,
ALTER COLUMN start_longitude TYPE DOUBLE PRECISION,
ALTER COLUMN stop_latitude TYPE DOUBLE PRECISION,
ALTER COLUMN stop_longitude TYPE DOUBLE PRECISION;

ALTER TABLE hauls
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION,
ADD COLUMN vessel_length_group INT NOT NULL GENERATED ALWAYS AS (TO_VESSEL_LENGTH_GROUP (vessel_length)) STORED,
ALTER COLUMN start_latitude TYPE DOUBLE PRECISION,
ALTER COLUMN start_longitude TYPE DOUBLE PRECISION,
ALTER COLUMN stop_latitude TYPE DOUBLE PRECISION,
ALTER COLUMN stop_longitude TYPE DOUBLE PRECISION,
ALTER COLUMN wind_speed_10m TYPE DOUBLE PRECISION,
ALTER COLUMN wind_direction_10m TYPE DOUBLE PRECISION,
ALTER COLUMN air_temperature_2m TYPE DOUBLE PRECISION,
ALTER COLUMN relative_humidity_2m TYPE DOUBLE PRECISION,
ALTER COLUMN air_pressure_at_sea_level TYPE DOUBLE PRECISION,
ALTER COLUMN precipitation_amount TYPE DOUBLE PRECISION,
ALTER COLUMN cloud_area_fraction TYPE DOUBLE PRECISION,
ALTER COLUMN water_speed TYPE DOUBLE PRECISION,
ALTER COLUMN water_direction TYPE DOUBLE PRECISION,
ALTER COLUMN salinity TYPE DOUBLE PRECISION,
ALTER COLUMN water_temperature TYPE DOUBLE PRECISION,
ALTER COLUMN ocean_climate_depth TYPE DOUBLE PRECISION,
ALTER COLUMN sea_floor_depth TYPE DOUBLE PRECISION;

ALTER TABLE fiskeridir_vessels
ALTER COLUMN "length" TYPE DOUBLE PRECISION,
ALTER COLUMN "width" TYPE DOUBLE PRECISION,
ADD COLUMN fiskeridir_length_group_id INT NOT NULL GENERATED ALWAYS AS (TO_VESSEL_LENGTH_GROUP (LENGTH)) STORED;

ALTER TABLE catch_areas
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION;

ALTER TABLE catch_main_areas
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION;

ALTER TABLE aqua_culture_register
ALTER COLUMN locality_kap TYPE DOUBLE PRECISION,
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION;

ALTER TABLE aqua_culture_register_species
ALTER COLUMN till_kap TYPE DOUBLE PRECISION;

ALTER TABLE ports
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION;

ALTER TABLE port_dock_points
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION;
