ALTER TABLE vms_positions
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION,
ALTER COLUMN speed TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION;
