ALTER TABLE ais_positions
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION,
ALTER COLUMN course_over_ground TYPE DOUBLE PRECISION,
ALTER COLUMN rate_of_turn TYPE DOUBLE PRECISION,
ALTER COLUMN speed_over_ground TYPE DOUBLE PRECISION,
ALTER COLUMN distance_to_shore TYPE DOUBLE PRECISION;

ALTER TABLE current_ais_positions
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION,
ALTER COLUMN course_over_ground TYPE DOUBLE PRECISION,
ALTER COLUMN rate_of_turn TYPE DOUBLE PRECISION,
ALTER COLUMN speed_over_ground TYPE DOUBLE PRECISION,
ALTER COLUMN distance_to_shore TYPE DOUBLE PRECISION;

ALTER TABLE ais_area
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION,
ALTER COLUMN course_over_ground TYPE DOUBLE PRECISION,
ALTER COLUMN rate_of_turn TYPE DOUBLE PRECISION,
ALTER COLUMN speed_over_ground TYPE DOUBLE PRECISION,
ALTER COLUMN distance_to_shore TYPE DOUBLE PRECISION;

ALTER TABLE vms_positions
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude TYPE DOUBLE PRECISION,
ALTER COLUMN speed TYPE DOUBLE PRECISION,
ALTER COLUMN vessel_length TYPE DOUBLE PRECISION;
