[package]
name = "duckdb-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kyogre-core = { path = "../kyogre-core", features = ["utoipa"] }
fiskeridir-rs = { workspace = true }
duckdb = { version = "0.8", features = ["r2d2", "bundled"] }
r2d2 = { version = "0.8" }
config = { version = "0.13.3", features = ["yaml"] }
tracing = "0.1.37"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
chrono = { version = "0.4.26", features = ["serde"] }
error-stack = { workspace = true }
orca-core = { workspace = true, features = ["telemetry"] }
orca-statemachine = { version = "0.39.0", registry = "orcalabs-orcastrator", features = [
] }
num-traits = "0.2.16"
async-trait = "0.1.72"
humantime-serde = "1.1.1"

tonic = { version = "0.9.2", features = ["gzip"] }
prost = "0.11"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1.29.1", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
] }
tokio-stream = { version = "0.1.14", features = ["net"] }

[dev-dependencies]
futures = "0.3.28"
tokio-stream = { version = "0.1.14", features = ["net"] }
tracing-subscriber = "0.3.17"
rand = "0.8.5"
dockertest = { version = "0.3.1", registry = "orcalabs-orcastrator" }
postgres = { path = "../postgres" }
orca-core = { workspace = true, features = ["dockertest"] }

[build-dependencies]
tonic-build = "0.9"
