log_level: Info
num_fuel_estimation_workers: 8
current_positions_batch_size: 1000
tracing_mode: Regular
postgres:
  ip: localhost
  port: 5532
  username: postgres
  password: test123
  max_connections: 64
  log_statements: Disable
  application_name: kyogre-processors
