log_level: Debug
port: 5000
postgres:
  ip: postgres
  port: 5432
  username: postgres
  password: test123
  max_connections: 10
  log_statements: Enable
duck_db:
  max_connections: 10
  cache_mode: ReturnError
  refresh_interval: 10m
  storage: Memory
