log_level: Debug
port: 5000
postgres:
  ip: localhost
  port: 5532
  username: postgres
  password: test123
  max_connections: 10
  log_statements: Enable
  application_name: kyogre-duckdb
duck_db:
  max_connections: 10
  cache_mode: ReturnError
  refresh_interval: 10m
  storage: Memory
