name: Docker build and push images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - src/**/*
      - dockerfiles/**/*

jobs:
  images:
    uses: orcalabs/github-actions/.github/workflows/images.yml@master
    secrets: inherit
    with:
      keys: |
        database-migrator
        ais-consumer
        fishery-api
        engine
      object: '{
           "database-migrator" : {
              "aks-path" : "pre-deploy/kyogre",
              "dockerfile" : "dockerfiles/database-migrator/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/database-migrator"
           },
           "ais-consumer" : {
              "aks-path" : "apps/base/kyogre",
              "dockerfile" : "dockerfiles/ais-consumer/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/ais-consumer"
           },
           "engine" : {
              "aks-path" : "apps/base/kyogre",
              "dockerfile" : "dockerfiles/engine/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/engine"
           },
           "fishery-api" : {
              "aks-path" : "apps/base/kyogre",
              "dockerfile" : "dockerfiles/fishery-api/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/fishery-api"
           }
        }'
      aks-repo: orcalabs/aks
