name: Build test-db master

on:
  push:
    branches:
      - master
    paths:
      - src/postgres/migrations/**
      - src/postgres/test_migrations/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/cache-cargo-install-action@v2
        name: install sqlx
        with:
          tool: sqlx-cli

      - name: install postgres 16
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
          sudo apt update
          sudo apt install postgresql-client-16

      - name: Setup rust
        uses: orcalabs/github-actions/rust-setup@master
        with:
          cloudsmith-api-key: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: migrate db
        run: |
          export DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432
          cargo sqlx migrate run --source src/postgres/migrations
          cargo sqlx migrate run  --ignore-missing --source src/postgres/test_migrations

          cd scripts/rust/gen-test-data
          cargo run
          cd ../../../

          mkdir src/master_migrations

          export PGPASSWORD=postgres
          pg_dump -h localhost -U postgres | grep -v '^CREATE SCHEMA' | grep -v '^COMMENT ON' > src/master_migrations/1231332_db.sql

      - uses: docker/setup-buildx-action@v3
        name: build and push db
        # See related issues
        # https://github.com/docker/build-push-action/issues/761#issuecomment-1575006515
        # https://github.com/moby/buildkit/issues/3969
        with:
          driver-opts: |
            image=moby/buildkit:v0.11.6
            network=host
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io/orcalabs/kyogre
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: dockerfiles/test-db/Dockerfile
          tags: ghcr.io/orcalabs/kyogre/test-postgres:master
          build-args: |
            MIGRATIONS_DIR_PATH=src/master_migrations
            TEST_MIGRATIONS_DIR_PATH=src/master_migrations
