name: Docker build and push images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - src/**/*
      - dockerfiles/**/*

jobs:
  images:
    uses: orcalabs/github-actions/.github/workflows/images.yml@master
    secrets: inherit
    with:
      keys: |
        database-migrator
        fishery-api
        duckdb
      object: '{
           "database-migrator" : {
              "aks-path" : "pre-deploy/kyogre",
              "dockerfile" : "dockerfiles/database-migrator/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/database-migrator"
           },
           "fishery-api" : {
              "aks-path" : "apps/base/kyogre",
              "dockerfile" : "dockerfiles/fishery-api/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/fishery-api"
           },
           "duckdb" : {
              "aks-path" : "apps/base/kyogre",
              "dockerfile" : "dockerfiles/duckdb/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/duckdb"
           }
        }'
      aks-repo: orcalabs/aks
