name: Docker build and push images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - src/**/*
      - dockerfiles/**/*

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/orcalabs
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: dockerfiles/ais-consumer/Dockerfile
          push: true
          tags: ghcr.io/orcalabs/kyogre/ais-consumer:${{ github.sha }}
          secrets: |
            git-credentials=${{ secrets.CLOUDSMITH_GIT_API_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: dockerfiles/database-migrator/Dockerfile
          push: true
          tags: ghcr.io/orcalabs/kyogre/database-migrator:${{ github.sha }}
          secrets: |
            git-credentials=${{ secrets.CLOUDSMITH_GIT_API_KEY }}

