name: Docker build and deploy images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - src/**/*
      - dockerfiles/**/*
jobs:
  images:
    uses: orcalabs/github-actions/.github/workflows/container-apps-deploy.yml@master
    secrets: inherit
    with:
      keys: |
        duckdb
        fishery-api
        ais-consumer
        engine
        database-migrator
      object: '{
           "duckdb" : {
              "container-app-name" : "dev-kyogre-duck-db",
              "dockerfile" : "dockerfiles/duckdb/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/duckdb"
           },
           "fishery-api" : {
              "container-app-name" : "dev-kyogre-fishery-api",
              "dockerfile" : "dockerfiles/fishery-api/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/fishery-api"
           },
           "ais-consumer" : {
              "container-app-name" : "dev-kyogre-ais-consumer",
              "dockerfile" : "dockerfiles/ais-consumer/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/ais-consumer"
           },
           "engine" : {
              "container-app-name" : "dev-kyogre-engine",
              "dockerfile" : "dockerfiles/engine/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/engine"
           },
           "database-migrator" : {
              "dockerfile" : "dockerfiles/database-migrator/Dockerfile",
              "registry" : "ghcr.io/orcalabs/kyogre/database-migrator"
           }
        }'
      resource-group: dev
      container-app-env-name: dev-kyogre

