name: Update OpenApi specs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - src/**/*

jobs:
  openapi:
    uses: orcalabs/github-actions/.github/workflows/openapi.yml@openapi
    secrets: inherit
    with:
      dependencies: protobuf-compiler
      object: '[
          {
            "bin": "web-api-openapi",
            "terraform-path": "dev/api-swaggers/fishery-api.json"
          }
        ]'
      terraform-repo: orcalabs/azure-terraform
