name: Rust Check

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always

jobs:
  rust-check:
    uses: orcalabs/github-actions/.github/workflows/rust_verify.yml@master
    secrets: inherit
    with:
      dependencies: protobuf-compiler
      pip-packages: xgboost pandas scikit-learn
      image-build-command: docker build -f dockerfiles/test-db/Dockerfile -t ghcr.io/orcalabs/kyogre/test-postgres .
      check-sqlx: true
      sqlx-migrations-dir: postgres
      postgres-version: postgis/postgis:15-3.4-alpine
      openapi-bins: |
        web-api-openapi
      cargo-test-features: all-tests
