name: Rust Check

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always

jobs:
  rust-check:
    uses: orcalabs/github-actions/.github/workflows/rust_verify.yml@buildjet
    secrets: inherit
    with:
      dependencies: protobuf-compiler
      image-build-command: docker build -f dockerfiles/test-db/Dockerfile -t ghcr.io/orcalabs/kyogre/test-postgres .
      check-sqlx: true
      postgres-version: postgis/postgis:14-3.3-alpine
      openapi-bins: |
        web-api-openapi
