name: Rust Check

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always

jobs:
  rust-check:
    uses: orcalabs/github-actions/.github/workflows/rust_verify.yml@master
    secrets: inherit
    with:
      dependencies: protobuf-compiler
      pip-requirements: scripts/python/fishing_predictor/requirements.txt
      image-build-command: docker build -f dockerfiles/test-db/Dockerfile -t ghcr.io/orcalabs/kyogre/test-postgres
        --build-arg MIGRATIONS_DIR_PATH=src/postgres/migrations
        --build-arg TEST_MIGRATIONS_DIR_PATH=src/postgres/test_migrations .
      image-pull-command: docker pull ghcr.io/orcalabs/kyogre/test-postgres:master
      check-sqlx: true
      sqlx-migrations-dir: postgres
      postgres-version: postgis/postgis:16-3.4-alpine
      openapi-bins: |
        web-api-openapi
      wait-for-check-name: build-test-db
