name: Rust Check

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://127.0.0.1:5432?user=postgres&password=postgres

jobs:
  rust-check:
    uses: orcalabs/github-actions/.github/workflows/rust_verify.yml@master
    secrets: inherit
    with:
      dependencies: protobuf-compiler
      src-dir: src
      image-build-command: docker build -f dockerfiles/test-db/Dockerfile -t ghcr.io/orcalabs/kyogre/test-postgres .
  sqlx-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          shared-key: sqlx
          workspaces: src
      - name: check sqlx query cache
        run: |
          cd src
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
          git config --global credential.helper store
          echo '${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}' > ~/.cargo/config
          echo '${{ secrets.CLOUDSMITH_GIT_API_KEY }}' > ~/.git-credentials
          cargo install sqlx-cli --no-default-features --features postgres,rustls
          sqlx migrate run --source postgres/migrations
          cargo sqlx prepare --merged --check
  openapi-check:
    runs-on: ubuntu-latest
    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          shared-key: shared
          workspaces: src
      - name: Produce OpenApi spec
        run: |
          cd src
          cargo run --bin web-api-openapi | cat > web-api/openapispec.json
      - name: Validate OpenAPI spec
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: src/web-api/openapispec.json
          ignore-error: ignore-openapi-error.js
