name: Update cache

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  update-rust-cache:
    uses: orcalabs/github-actions/.github/workflows/rust_build_cache.yml@buildjet
    secrets: inherit
    with:
      dependencies: protobuf-compiler
      src-dir: src
      build-sqlx-cache: true
      postgres-version: postgis/postgis:14-3.3-alpine
