name: Update rust dependencies

on:
  schedule:
    # Runs "At 07:00 on Monday." (see https://crontab.guru)
    - cron: '0 7 * * 1'

jobs:
  update_dependencies:
    uses: orcalabs/github-actions/.github/workflows/rust_update.yml@master
    secrets: inherit
